### ISSUE TITLE
[Scratchpad] Focus lost when closing scratchpad

### ISSUE THREAD

**Issue by skbolton** [Nooo37/bling#119]
I have a two monitor setup configured like so. The horizontal monitor is my primary monitor.

```
         ┌────────────────┐
         │                │
         │                │
         │                ├──────────────────────────┐
         │                │                          │
         │                │                          │
         │                │                          │
         │                │                          │
         │                │                          │
         │                │                          │
         │                │                          │
         │                │                          │
         │                │                          │
         │                ├──────────────────────────┘
         │                │
         └────────────────┘
```
If I have a scratchpad defined to animate up or down and I open and close it on my main monitor then none of the other clients on that screen gain focus. If the scratchpad is defined to animate left or right things work correctly - a client gains focus after scratch animates off screen.

I am guessing this has something to do with animating into a screen area that is not covered by a monitor output.

**Comment by Nooo37** [comment]
Can you provide the relevant configuration snippet and do the classic "expected behavior" vs "actual behavior". I don't know how to reproduce the issue rn

**Comment by skbolton** [comment]
> This is Xorg problem, when window goes outside of visible are then lost forcues because window manager doesn't know what do with it, have you tried `require("awful.autofocus")` somewhere in your config files e.g. `rc.lua`? This function _should_ automatically focus new window when it's becomes "visible".

Yeah it doesn't seem to catch this and handle it.

**Comment by flaviusbuffon** [comment]
have this problem solved?k

**Comment by skbolton** [comment]
I havent refactored how I got around it so it’s a bit messy but it has worked so far. Although it has some edge cases that puts things in a weird state.

[here](https://github.com/skbolton/titan/blob/1a3989eda7b051138e9c33c843bad1f58125f461/awesome/awesome/keys.lua#L233) is where in my keybinds I call the function to open or close a scratchpad. This then sets a flag of the previous focused client. That function implementation is [here](https://github.com/skbolton/titan/blob/1a3989eda7b051138e9c33c843bad1f58125f461/awesome/awesome/elemental/scratchpad.lua#L240)

lastly every one of my scratchpads has a signal to handle when it is closed. https://github.com/skbolton/titan/blob/1a3989eda7b051138e9c33c843bad1f58125f461/awesome/awesome/elemental/scratchpad.lua#L50

Again I hacked this up and it’s mostly working but improvements can definitely be made.

**Comment by flaviusbuffon** [comment]
i used your code, there is no error now, but scratchpad can't be called.

`local awful = require("awful")
local bling = require("bling")
local beautiful = require("beautiful")
local dpi = beautiful.xresources.apply_dpi
local rubato = require("rubato")
local helpers = require("helpers")
local naughty = require("naughty")


local _M = { last_focused_client = nil }

local rubato_with_defaults = function(overrides)
  return rubato.timed {
    pos = overrides.pos or 0,
    rate = overrides.rate or 120,
    easing = overrides.easing or rubato.quadratic,
    intro = overrides.intro or 0.1,
    duration = overrides.duration or 0.4,
    awestore_compat = true
  }
end

local restore_client = function ()
  if (_M.last_focused_client) then
    _M.last_focused_client:jump_to()
    _M.last_focused_client = nil
  end
end

local terminal_scratch = function(screen_geometry)
  -- clamp the width and height to always fit on screen
  local width = math.min(screen_geometry.width * 0.90, 2400)
  local height = math.min(600, screen_geometry.height - 20)
  local x = (screen_geometry.width - width) / 2

  local terminal = bling.module.scratchpad:new {
    command = "alacritty --class term_pad",
    rule = {instance = "term_pad"},
    sticky = true,
    autoclose = false,
    geometry = {x = x, y = dpi(60) + screen_geometry.y, height = height, width = width},
    floating = true,
    reapply = true,
    rubato = {
      y = rubato_with_defaults {
        pos = -height
      }
    }
  }

  terminal:connect_signal("turn_off", restore_client)
  awesome.connect_signal("scratch::terminal", function() terminal:toggle() end)

  return terminal
end


local spotify_scratch = function(screen_geometry)
  -- clamp the width and height to always fit on screen
  local width = math.min(screen_geometry.width * 0.90, 2400)
  local height = math.min(1000, screen_geometry.height - 20)
  local x = (screen_geometry.width - width) / 2
  local y = ((screen_geometry.height - height) / 2) + screen_geometry.y

  local spotify = bling.module.scratchpad:new {
    command = "spotify",
    rule = { instance = "spotify"},
    sticky = true,
    autoclose = false,
    floating = true,
    geometry = {x = x, y = y, height = height, width = width},
    reapply = true,
    rubato = {
      y = rubato_with_defaults {
       pos = screen_geometry.height * 2
      }
    }
  }

  bench:connect_signal("turn_off", restore_client)
  awesome.connect_signal("scratch::bench", function() bench:toggle() end)

  return bench
end

local tg_scratch = function(screen_geometry)
  local width = math.min(screen_geometry.width / 3, 1400)
  local height = screen_geometry.height * 0.90
  local x = (screen_geometry.width - width - 20) + screen_geometry.x
  local y = (screen_geometry.height - height) / 2

  local tg = bling.module.scratchpad:new{
      command = "telegram-desktop",
      rule = { instance = "telegram-desktop" },
      sticky = false,
      autoclose = false,
      floating = true,
      geometry = {x = x, y = y, height = height, width = width},
      reapply = true,
      rubato = {
        x = rubato_with_defaults {
          pos = screen_geometry.width + width + screen_geometry.x
        }
      }
  }

  quest:connect_signal("turn_off", restore_client)
  awesome.connect_signal("scratch::quest", function() quest:toggle() end)

  return quest
end


-- initialize scratchpads
_M.init = function()
    local scratchpads = {
      terminal = terminal_scratch,
      spotify = spotify_scratch,
      tg = tg_scratch
    }

    for name, scratch in pairs(scratchpads) do
      _M[name] = scratch(screen.primary.geometry)
    end
end

_M.toggle_and_restore = function (scratchpad)
  if (not _M.last_focused_client) then
    _M.last_focused_client = client.focus
  end

  awesome.emit_signal("scratch::" .. scratchpad)
end


return _M

`
``
	awful.key({ superkey, "Shift" }, "Return", function()
		-- term_scratch:toggle()
        scratchpad.toggle_and_restore("terminal")
	end, {
		description = "alacritty scratchpad",
		group = "scratchpad",
	}),

**Comment by skbolton** [comment]
@flaviusbuffon I am having an error based off changes added to master a few days ago. Are you getting the same error I reported [here](https://github.com/BlingCorp/bling/issues/146)

**Comment by flaviusbuffon** [comment]
no, i just repaired my fault in lua config. Now it can work mostly!

**Comment by flaviusbuffon** [comment]
> @flaviusbuffon I am having an error based off changes added to master a few days ago. Are you getting the same error I reported [here](https://github.com/BlingCorp/bling/issues/146)

I feel fuzzy that can your scratchpad config make effect when I am using three screen like this:
![image](https://user-images.githubusercontent.com/44057232/144252817-f576569b-e72b-4365-a0ee-a19477057280.png)

**Comment by skbolton** [comment]
@flaviusbuffon Feel free to make an issue on my dotfiles [repo](https://github.com/skbolton/titan) and I can try and help you

**Comment by skbolton** [comment]
But I think we should let this issue be closed here.
