### ISSUE TITLE
theme.mstab_dont_resize_flaves = true doesnt seem to work

### ISSUE THREAD

**Issue by ninelore** [Nooo37/bling#14]
I still see a small window behind a transparent terminal in mstab

![image](https://user-images.githubusercontent.com/21343557/105253894-af4e0700-5b80-11eb-8870-bb77dce18fd9.png)

You can find my configs [here](https://github.com/ninelore/dotfiles/tree/master/config/awesome)

Btw a side question. Maybe im dumb but i couldnt find out how to use the keybind tabbed.pick mentioned in ToDo and #13 
can you clarify what function i need to bind for that?

Thank you in advance

**Comment by branwright1** [comment]
Hello, try to type ``slaves`` not ``flaves`` I hope it should work since every non ``master`` is named ``slave``

**Comment by Nooo37** [comment]
@ninelore Bran is right. It was a typo in the template file. Sorry for that. Does it work with the actual variable name?

**Comment by ninelore** [comment]
yes it works thanks. Whats with my side question?

**Comment by branwright1** [comment]
@ninelore This works for me, put it in ``rc.lua`` or whatever you are storing keys and edit for your needs
```Lua 
 -- Bling tabbar keybinds
    awful.key({ modkey }, "t", function () bling.module.tabbed.pick() end,
        {description = "Enable tabbar for focused client", group = "Bling"}),
    awful.key({ modkey, "Shift" }, "t", function () bling.module.tabbed.pop() end,
        {description = "Remove focused client from tabbar", group = "Bling"}),
    awful.key({ modkey }, "Tab", function () bling.module.tabbed.iter() end,
        {description = "Iter through all tabs", group = "Bling"}),
```

**Comment by ninelore** [comment]
isnt `bling.module.tabbed.pick` for the mouse? it got mentioned it it possible to select with the keyboard, but i cant find anything on how exactly

**Comment by Nooo37** [comment]
@ninelore The only other option to add clients is with the `bling.module.tabbed.pick_with_dmenu` function. It defaults to rofi as the external dmenu application but you can also pass another command as a string to make it work with dmenu and what not (for example with `bling.module.tabbed.pick_with_dmenu("dmenu")`). It is bind the same way that the other functions are. And you are right, I should have added that to the readme.

**Comment by ninelore** [comment]
Fair enough. Thank you
