### ISSUE TITLE
A wallpaper module

### ISSUE THREAD

**Issue by Grumph** [Nooo37/bling#15]
Lately, I wrote a declarative wallpaper setter module.

It can do:

- sequential or random from a list, with a "change every" timer
- schedule based change (as seen in [dynamic-wallpaper](https://github.com/manilarome/awesome-glorious-widgets/blob/master/dynamic-wallpaper/init.lua)), you can have a safe for work wallpaper from 09:00 to 18:00 and a random wallpaper form the NSFW folder the rest of the time for example.
- the list can contain what gears.wallpaper supports (color, cairo stuff, image file), directories containing images, functions (with this you can use a list of different bling.module.tiled_wallpaper for example)
- a pre-configured beautiful.theme_assets.wallpaper with standard theme colors by default

I wrote the [documentation](http://capcat.net/tmp/wallpaper/).

Here is [the code](https://bitbucket.org/grumph/home_config/src/master/.config/awesome/wallpaper.lua)  from my dotfiles.

I was thinking about making it a standalone module, but I discovered bling a few days ago, and I think this module could fit in bling.

Should I use my time to write a PR here, or would it be better for me to continue in the standalone path ?

Note: my module is for awesome-git, I think I use some functions/mechanisms that are not available in 4.3, I did not test it with multiple screens yet, and the code needs some optimizations.

**Comment by branwright1** [comment]
Hello, I think it's really nice module but I don't think it will work good with bling since your module since is made for git version of awesome, bling itself is designed for stable version (works with git as well) but this new wallpaper module will generate some breaking config errors for non-git users

**Comment by Grumph** [comment]
That's what I thought.
I will go for the standalone git version for now, and when I have time I will try to backport it for integration in bling.

Thanks for the feedback.

**Comment by JavaCafe01** [comment]
@Grumph Hey there, we just tested out your module and it does work on stable. We would love to see a PR someday!

**Comment by Grumph** [comment]
How much am I allowed to reorganize the existing code ?
I'm thinking about :
 - move the helpers to a dedicated folder, with categories, a bit like gears with e.g. "bling.helpers.shape.rrect" or "bling.helpers.color.darken". 
 - add ldoc info for functions I touch/move (but not necessarily my code).

**Comment by Nooo37** [comment]
Moving the helpers functions to a dedicated folder sounds very reasonable and should have probably already happened. 
Adding docs to where they are appropriate also adds value but I wouldn't consider it necessary to be honest. We just aren't really striving towards a full fledged code documentation at the moment considering how small the module still is and seeing how other awesome modules went well without one. That being said, if you feel like some your code or some of the existing code would be easier to understand that way, you are free to add clearity in form of a comment or a LDoc. :+1:
