### ISSUE TITLE
[Scratchpad] Discussion and ideas 

### ISSUE THREAD

**Issue by branwright1** [Nooo37/bling#19]
Hello, I found a way how to implement scratchpad as keybind or button, default awesome titlebar has "pin" icon which exec function "ontop". This function keep "pinned window" on top of other windows and it is visible on other tags. I think we can implement it as "keybind" like `bling.scratchpad_toggle()` in order to use focused window as scratchpad e.g. with selected geometry and on screen position

**Comment by Nooo37** [comment]
There should probably be one function to create a scratchpad which then holds his own toggle function like that:
```lua
local discordpad = bling.module.scratchpad("discord", {instance = "discord"}, args) -- declares the scratchpad
discordpad.toggle() -- toggles the scratchpad on and off
```
Whereas the first argument is how to spawn the scratchpad (that would probably be something like `alacritty --class scratchpad` for a terminal scratchpad), the second argument would be a rule to identify the window after spawning it and `args` would be a table holding optional configurations like the size of the scratchpad, its position, whether it is sticky, whether it should autoclose on unfocus etc. That way, we would allow for multiple ones simultaneously and all sort of scratchpads.

**Comment by branwright1** [comment]
So, to get scratchpad to work with preferd window we need two rules with toggle function as keybind for selected window class. 
- `sticky` - this rule keeps scratchpad window in selected possition across all tags 
- `ontop` - this rule keeps selected window on top of each others
