### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by JavaCafe01** [Nooo37/bling#20]
As bling grows, we need to get rid of the readme and make actual documentation. Any ideas on what to use or generate? If we choose on one, I can get started.

**Comment by branwright1** [comment]
I think wiki section with pages for each module is enough. Alternativelyy we can create website hosted on github with documentation website generator like this https://docsify.js.org/#/

**Comment by JavaCafe01** [comment]
> we can create website hosted on github with documentation website generator like this https://docsify.js.org/#/

I like this generator, so far with our current readme it looks like this:

![image](https://user-images.githubusercontent.com/33443763/107864606-b7f9cc00-6e12-11eb-84c5-04055d08bca7.png)

**Comment by branwright1** [comment]
Actually this is very nice, now we wait fro @Nooo37 comment on this :D

**Comment by Nooo37** [comment]
Docsify is very good looking and probably more appealing than a github wiki. We should just make sure to add support for lua syntax highlighting because especially longer code blocks like the ones on the declarative wallpaper module become unreadable without it.

**Comment by JavaCafe01** [comment]
> We should just make sure to add support for lua syntax highlighting because especially longer code blocks like the ones on the declarative wallpaper module become unreadable without it.

Yup, it uses prism for syntax highlighting.
![image](https://user-images.githubusercontent.com/33443763/108039880-85f29080-6ff1-11eb-9d98-451807ea953f.png)

**Comment by JavaCafe01** [comment]
@branwright1 @Nooo37 i finished the docs up in the docs branch, take a look if there are any edits needed or if there is anything i forgot

also @Nooo37 if this is all good i think u should host it on github

**Comment by branwright1** [comment]
For now I found only 2 problems:
- Images/gifs at the top can take a while to be loaded or sometimes need to reload website in order to see them
- I think this text should be above gif or under it because looks a bit weird compared to other pages. 
![img](https://i.imgur.com/EjIdmJx.png) 

Small suggestion:
- Reduce a bit size of preview images/gifs on every pages, they are too big imo.
- ![img](https://i.imgur.com/xKUyCtm.png)

**Comment by JavaCafe01** [comment]
done with #21 , will reduce size @branwright1
