### ISSUE TITLE
Add topics to the project

### ISSUE THREAD

**Issue by Grumph** [Nooo37/bling#22]
It could be nice to add some topics to the project, at least "awesomewm" so the project can be discovered through https://github.com/topics/awesomewm.

Idea from [this comment on Reddit](https://old.reddit.com/r/awesomewm/comments/lnb5f2/awesome_awesomewm/gnzq6wa/).

**Comment by Nooo37** [comment]
Alright. I also added "wm" as that topic seems to go into the same domain of possible users. I think tags such as "layout", "module" or "utilities" aren't helpful at all. I'm probably just too uncreative. If anyone can come up with another meaningful tag, please let us know.

**Comment by branwright1** [comment]
I think @Grumph can close this issue since it's done.
