### ISSUE TITLE
Adding a license  

### ISSUE THREAD

**Issue by Nooo37** [Nooo37/bling#25]
We should have added a license at the very beginning of the project, but we missed out on that. So I'll just ask all contributors, @JavaCafe01, @Grumph, @branwright1 and @Bysmutheye, whether or not you all agree on placing the project (which includes your work) under a FOSS license. 

The particular license that we should use can be debated on this thread, but I'll just start by throwing the MIT license into the discussion.

**Comment by JavaCafe01** [comment]
Random Ping @Grumph for checking this issue again lol
