### ISSUE TITLE
Errors with Flash Focus

### ISSUE THREAD

**Issue by JavaCafe01** [Nooo37/bling#4]
If you quickly close a client right after focus, errors will produce. My guess it is because the timer is still running when client is closed.

![gif_2020-10-2817:11:55](https://user-images.githubusercontent.com/33443763/97510003-ff7e4a00-1940-11eb-814d-6d055e416069.gif)

**Comment by Nooo37** [comment]
Leave a comment here if you can reproduce that issue because I can't.

**Comment by JavaCafe01** [comment]
oof

**Comment by JavaCafe01** [comment]
I can still reproduce, this only happens when you kill a 
window after recently focusing it.


![gif_2020-11-2316:50:55](https://user-images.githubusercontent.com/33443763/100032165-3ca4f300-2dac-11eb-976c-262b85f72222.gif)

**Comment by findingxyz** [comment]
I have this problem too

**Comment by Nooo37** [comment]
@findingxyz It should be fixed now.

**Comment by findingxyz** [comment]
> @findingxyz It should be fixed now.

yes it is, thanks
